<?php
 return [
        'Addictologie',
        'Allergologie',
        'Anatomie et cytopathologie',
        'Anesthésie-réanimation',
        'Biologie médicale',
        'Dermatologie et vénérologie',
        'Endocrinologie-diabétologie-nutrition',
        'Génétique médicale',
        'Gériatrie',
        'Gynécologie médicale',
        'Hématologie',
        'Hépato-gastro-entérologie',
        'Médecine cardiovasculaire',
        'Médecine d’urgence',
        'Médecine du sport',
        'Médecine du travail',
        'Médecine générale',
        'Maladies infectieuses et tropicales',
        'Médecine intensive-réanimation',
        'Médecine interne',
        'Médecine nucléaire',
        'Médecine physique et de réadaptation',
        'Médecine vasculaire',
        'Néphrologie',
        'Neurologie',
        'Oncologie',
        'Pédiatrie',
        'Pneumologie',
        'Psychiatrie',
        'Radiologie et imagerie médicale',
        'Rhumatologie',
        'Santé publique',
        'Chirurgie infantile',
        'Chirurgie maxillo-faciale',
        'Chirurgie orale',
        'Chirurgie orthopédique et traumatologique',
        'Chirurgie thoracique et cardiovasculaire',
        'Chirurgie vasculaire',
        'Chirurgie viscérale et digestive',
        'Gynécologie-obstrétrique',
        'Neurochirurgie',
        'Ophtalmologie',
        'Oto-Rhino-Laryngologie',
        'Urologie',
        'Agents infectieux',
        'Biologie générale',
        'Biologie de la reproduction',
        'Hématologie et immunologie',
        'Médecine moléculaire, génétique et pharmacologie'
 ];
